### PR TITLE
Refine template peak radius fix

### LINKED ISSUE #20: Refine template uses wrong peak radius
# Summary
Refine template compares the square of the distance to a found peak, to the peak radius, rather than the peak radius squared. This can lead to duplicate peaks in cases where the normalized peak is still spread over several pixels.

## Broken Code
https://github.com/bHimes/cisTEM_downstream_bah/blob/74d697f0c7da44e523ff825cd663ca3c44b11c85/src/programs/refine_template/refine_template.cpp#L588-L592

## Fix
Look to match_template for a verbatim fix. (Maybe this code shouldn't be duplicated?)
https://github.com/bHimes/cisTEM_downstream_bah/blob/74d697f0c7da44e523ff825cd663ca3c44b11c85/src/programs/match_template/match_template.cpp#L1845-L1846

## Enhancement
Also note that the loop is over the full image every time (as the original match_template was.) Also take this opportunity to improve the efficiency there. Here is the link to the match_template loop.
https://github.com/bHimes/cisTEM_downstream_bah/blob/74d697f0c7da44e523ff825cd663ca3c44b11c85/src/programs/match_template/match_template.cpp#L1894-L1930

### PR DESCRIPTION
**Pull request by ngrigorieff**
Fixes #20
Ignore .vscode settings

### CODE REVIEW

File: src/programs/refine_template/refine_template.cpp [hunk 1]
```diff
@@ -557,6 +557,7 @@ bool RefineTemplateApp::DoCalculation()
 
 	best_scaled_mip.CopyFrom(&scaled_mip_image);
 	current_peak.value = FLT_MAX;
+	min_peak_radius = powf(min_peak_radius, 2);
```
Comment (bHimes) [inline src/programs/refine_template/refine_template.cpp:560]: I would prefer to create another variable min_peak_radius_squared rather than silently overwriting min_peak_radius given that the comparison

**if ( sq_dist_x + sq_dist_y <= min_peak_radius )**

is then a bit less clear. Future me doesn't want to have to figure out why we compare the sq_dist to the min_rad : )

@ngrigorieff do you not agree with the enhancement portion of issue #20? It is okay with me if we tackle those in separate PRs, but it seems to be a natural fit since the same tests for functionality can be used for both mods.

Comment (ngrigorieff) [reply src/programs/refine_template/refine_template.cpp:560]: @bHimes Sure, please go ahead and make the change.

Comment (bHimes) [reply src/programs/refine_template/refine_template.cpp:560]: I could make changes, but that might somewhat defeat the purpose of the exercise! Please at least edit the variable, and optionally consider implementing the more efficient loop. Add these changes and push the resulting commit, and then I can pull this in to the main repo.

**Comment by bHimes** [comment]
Thanks @ngrigorieff I'm approving the PR but instead of ->master I'm merging it into a new branch with the same name as yours, that way I can add the loop enhancement prior to pushing up to the main. We'll go over integrating changes from upstream next.
